name: Test Action

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Message
        run: echo "Hello, world!"

      - name: Print GitHub Username
        run: echo "Triggered by GitHub User: ${{ github.actor }}"
