name: Test Action

on:
  push:
    branches:
      - main  # Trigger the action on the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "22f3001961@ds.study.iitm.ac.in"  # Treat email as a string in quotes
        run: echo "Hello, world!"  # Print 'Hello, world!' in the logs
